services:
  - type: web
    name: iam-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET_KEY
        generateValue: true
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /apidocs/
